apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: registry.redhat.io/rhel7:latest
      # image: centos:centos7 - works as well
      command:
        - echo
      args:
        - "Hello World"