###
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-build
spec:
##################### New content ###################
  inputs:
    resources:
      - name: task-repo
        type: git
  outputs:
    resources:
      - name: task-repo
        type: git
##################### New content ###################
  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/task-repo
      command: ["mvn"]
      args:
        - "compile"
    - name: ls
      image: registry.redhat.io/rhel7:latest
      workingDir: /workspace/task-repo
      command: ["ls"]
      args:
        - "-l"
        - "target/"