###
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:

##################### New content ###################
  workspaces:
  - name: maven-repo
##################### New content ###################

  params:
    - name: maven-goal
      description: The maven goal
      default: compile
  resources:
    inputs:
      - name: task-repo 
        type: git
    outputs:
      - name: task-repo 
        type: git

  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/task-repo
      command: ["mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(params.maven-goal)"