apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: maven-build-task-run-workspace
spec:
  taskRef:
    name: maven-build
  # serviceAccountName: pipeline
  inputs:
    resources:
      - name: task-repo
        resourceRef:
          name: spring-rest-git
  outputs:
    resources:
      - name: task-repo
        resourceRef:
          name: spring-rest-git
##################### New content ###################
  workspaces:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc
##################### New content ###################
     
