apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven-build-task-run-workspace-cache
spec:
  taskRef:
    name: maven-build
  # serviceAccountName: pipeline

  resources:
    inputs:
      - name: task-repo
        resourceRef:
          name: spring-rest-git
    outputs:
      - name: task-repo
        resourceRef:
          name: spring-rest-git

  workspaces:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc
      
