###
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-build
spec:
  inputs:
    resources:
      - name: source
        type: git
  outputs:
    resources:
      - name: source
        type: git
  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/source
      command: ["mvn"]
      args:
        - "package"
    - name: ls
      image: registry.redhat.io/rhel7:latest
      workingDir: /workspace/source
      command: ["ls"]
      args:
        - "-l"
        - "target/"