apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: spring-rest-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/paolocarta/spring-rest-tekton-pipeline.git