apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/paolocarta/spring-rest-tekton-pipeline.git
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-build
spec:
  inputs:
    resources:
      - name: source
        type: git
    # params:
    #   - name: directory
    #     description: Working directory parameter
    #     default: /workspace/workspace
  outputs:
    resources:
      - name: source
        type: git
  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/source
      command: ["mvn"]
      args:
        - "clean"
        - "install"