apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: maven-build-task-run
spec:
  taskRef:
    name: maven-build
  inputs:
    resources:
      - name: task-repo
        resourceRef:
          name: spring-rest-git
  outputs:
    resources:
      - name: task-repo
        resourceRef:
          name: spring-rest-git
      
