###
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-build
spec:
  workspaces:
  - name: maven-repo
  inputs:
    resources:
      - name: task-repo 
        type: git
    # params:
    #   - name: directory
    #     description: Working directory parameter
    #     default: /workspace/workspace
  outputs:
    resources:
      - name: task-repo 
        type: git
  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/source
      command: ["mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "package"
    - name: ls
      image: registry.redhat.io/rhel7:latest
      workingDir: /workspace/source
      command: ["ls"]
      args:
        - "-l"
        - "target/"