###
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-build
spec:
##################### New content ###################
  workspaces:
  - name: maven-repo
##################### New content ###################
  inputs:
    resources:
      - name: task-repo 
        type: git
    params:
      - name: maven-goal
        description: The maven goal
        default: compile
  outputs:
    resources:
      - name: task-repo 
        type: git
  steps:
    - name: maven-build
      image: maven:3.6.3-jdk-8-slim
      workingDir: /workspace/task-repo
      command: ["mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(inputs.params.maven-goal)"