apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: maven-build-task-run-workspace
spec:
  taskRef:
    name: maven-build
  # serviceAccountName: pipelines
  inputs:
    resources:
      - name: source
        resourceRef:
          name: spring-rest-git
  outputs:
    resources:
      - name: source
        resourceRef:
          name: spring-rest-git
##################### New content ###################
  workspaces:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc
##################### New content ###################
     
