apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tutorial-pipeline-run-1
spec:
  # serviceAccountName: pipelines
  pipelineRef:
    name: tutorial-pipeline
  resources:
    - name: pipe-repo
      resourceRef:
        name: spring-rest-git
  workspaces:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc